"""
Evaluation Metrics for AI DNA Architecture (Consolidated).
Implements all metrics from idea.md Sections 26, 37, and 38:
- S_E (Sample Efficiency): N_baseline / N_DNA
- L_behavior (Behavioral Divergence): D_KL(P_orig || P_regen)
- R_old (Retention Metric): P_old,new / P_old,old
- C_R (True Compression Ratio): |theta_model| / (|D| + |theta_G| + |theta_S|)
- C_compute (Compute Cost): alpha * T_seq + beta * M_peak + delta * M_total
- Delta_S_E (Generational Improvement): S_E(D_{n+1}) - S_E(D_n)
- FalsificationChecker: Automated failure criteria from Section 38
"""

import math
import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Dict, Any, Optional, List, Tuple
from dataclasses import dataclass, field


class EvaluationMetrics:
    """
    Standardized evaluation metrics for experimental validation.
    Consolidates all metrics from idea.md Sections 26, 37.
    """

    @staticmethod
    def sample_efficiency(steps_baseline: int, steps_dna: int) -> float:
        """
        S_E = N_baseline(P*) / N_DNA(P*)
        S_E > 1.0 indicates accelerated transfer learning.
        (Section 26 & 37.1)
        """
        if steps_dna <= 0:
            return 1.0
        return float(steps_baseline) / float(steps_dna)

    @staticmethod
    def behavioral_divergence(
        logits_orig: torch.Tensor,
        logits_regen: torch.Tensor,
    ) -> float:
        """
        L_behavior = E_x [ D_KL( P_orig || P_regen ) ]
        (Section 37.2)
        """
        p = F.softmax(logits_orig, dim=-1)
        log_q = F.log_softmax(logits_regen, dim=-1)

        kl = F.kl_div(log_q, p, reduction="batchmean", log_target=False)
        return kl.item()

    @staticmethod
    def retention_metric(perf_new: float, perf_old: float) -> float:
        """
        R_old = Perf_old(D_new) / Perf_old(D_old)
        (Section 17.2 & 37.3)
        """
        if perf_old <= 0:
            return 1.0
        return perf_new / perf_old

    @staticmethod
    def true_compression_ratio(
        model_parameters: int,
        dna_parameters: int,
        growth_engine_parameters: int = 0,
        residual_parameters: int = 0,
    ) -> float:
        """
        C_R = |theta_model| / (|D| + |theta_G| + |theta_S|)
        (Section 5 & 37.4)
        """
        denom = dna_parameters + growth_engine_parameters + residual_parameters
        if denom <= 0:
            return 1.0
        return float(model_parameters) / float(denom)

    @staticmethod
    def true_compression_ratio_from_model(
        genotype: "Genotype",
        phenotype_model: nn.Module,
        growth_engine: Optional[nn.Module] = None,
    ) -> float:
        """
        Convenience method to compute C_R directly from Genotype + PhenotypeNeuralNetwork objects.
        Includes |theta_G| (growth engine) and |theta_S| (residual parameters).
        (Section 5 — corrected formulation)
        """
        # |theta_model| — phenotype parameter count
        theta_model = sum(p.numel() for p in phenotype_model.parameters())

        # |D| — genotype genetic parameters
        theta_d = 0
        if genotype.dna_instinct.genetic_parameters:
            theta_d = sum(t.numel() for t in genotype.dna_instinct.genetic_parameters.values())

        # |theta_G| — growth engine parameters (CPPN + coordinate generator)
        theta_g = 0
        if growth_engine is not None:
            theta_g = sum(p.numel() for p in growth_engine.parameters() if isinstance(growth_engine, nn.Module))

        # |theta_S| — residual static parameters (norm layers, biases not generated by CPPN)
        theta_s = 0
        for name, param in phenotype_model.named_parameters():
            if "norm" in name or "ln" in name or ("bias" in name and "head" not in name):
                theta_s += param.numel()

        return EvaluationMetrics.true_compression_ratio(
            model_parameters=theta_model,
            dna_parameters=theta_d,
            growth_engine_parameters=theta_g,
            residual_parameters=theta_s,
        )

    @staticmethod
    def compute_cost(
        t_seq_ms: float,
        peak_mem_kb: float,
        total_mem_kb: float,
        alpha: float = 1.0,
        beta: float = 0.5,
        delta: float = 0.2,
    ) -> float:
        """
        C_compute = alpha * T_seq + beta * M_peak + delta * M_total
        (Section 9.1 & 37.5)
        """
        return alpha * t_seq_ms + beta * peak_mem_kb + delta * total_mem_kb

    @staticmethod
    def generational_improvement(s_e_new: float, s_e_old: float) -> float:
        """
        Delta_S_E(n) = S_E(D_{n+1}) - S_E(D_n)
        (Section 37.6)
        """
        return s_e_new - s_e_old


@dataclass
class FalsificationResult:
    """Result of a falsification criteria check."""
    criterion: str
    passed: bool
    value: float
    threshold: float
    message: str


class FalsificationChecker:
    """
    Implements falsification criteria from idea.md Section 38.
    The architecture is considered unsuccessful if controlled experiments consistently show:
    - Failure A: S_E <= 1 for DNA-generated models on unseen tasks
    - Failure B: No meaningful E_k / S_E correlation
    - Failure C: CPPN encoding destroys transfer advantage
    - Failure D: Repeated generations fail to improve transferability
    - Failure E: Fusion consistently destroys parent capabilities
    - Failure F: C_R ~ 1 (no compression advantage)
    """

    @staticmethod
    def check_sample_efficiency(s_e_values: List[float], threshold: float = 1.0) -> FalsificationResult:
        """Failure A: S_E <= 1 for DNA-generated models on unseen tasks."""
        if not s_e_values:
            return FalsificationResult("A", False, 0.0, threshold, "No S_E data provided")
        mean_se = sum(s_e_values) / len(s_e_values)
        passed = mean_se > threshold
        return FalsificationResult(
            "A", passed, mean_se, threshold,
            f"Mean S_E={mean_se:.3f} {'>' if passed else '<='} {threshold}"
        )

    @staticmethod
    def check_energy_transfer_correlation(
        e_k_values: List[float],
        s_e_values: List[float],
        min_correlation: float = 0.3,
    ) -> FalsificationResult:
        """Failure B: No meaningful relationship between E_k and S_E."""
        if len(e_k_values) < 3 or len(s_e_values) < 3:
            return FalsificationResult("B", False, 0.0, min_correlation, "Insufficient data points")

        n = min(len(e_k_values), len(s_e_values))
        e_vals = e_k_values[:n]
        s_vals = s_e_values[:n]

        # Pearson correlation
        mean_e = sum(e_vals) / n
        mean_s = sum(s_vals) / n
        cov = sum((e - mean_e) * (s - mean_s) for e, s in zip(e_vals, s_vals)) / n
        std_e = math.sqrt(sum((e - mean_e) ** 2 for e in e_vals) / n) + 1e-9
        std_s = math.sqrt(sum((s - mean_s) ** 2 for s in s_vals) / n) + 1e-9
        corr = cov / (std_e * std_s)

        passed = abs(corr) >= min_correlation
        return FalsificationResult(
            "B", passed, corr, min_correlation,
            f"Correlation(E_k, S_E)={corr:.3f}, |corr| {'≥' if passed else '<'} {min_correlation}"
        )

    @staticmethod
    def check_cppn_preserves_transfer(
        s_e_svd: float,
        s_e_cppn: float,
        max_degradation: float = 0.2,
    ) -> FalsificationResult:
        """Failure C: CPPN encoding destroys the transfer advantage found in SVD."""
        degradation = max(0.0, s_e_svd - s_e_cppn) / max(s_e_svd, 1e-9)
        passed = degradation <= max_degradation
        return FalsificationResult(
            "C", passed, degradation, max_degradation,
            f"CPPN degradation={degradation:.3f} {'≤' if passed else '>'} {max_degradation}"
        )

    @staticmethod
    def check_generational_improvement(
        s_e_per_generation: List[float],
    ) -> FalsificationResult:
        """Failure D: Repeated generations fail to improve transferability."""
        if len(s_e_per_generation) < 2:
            return FalsificationResult("D", False, 0.0, 0.0, "Insufficient generation data")
        improvements = [s_e_per_generation[i+1] - s_e_per_generation[i] for i in range(len(s_e_per_generation) - 1)]
        mean_improvement = sum(improvements) / len(improvements)
        passed = mean_improvement > 0
        return FalsificationResult(
            "D", passed, mean_improvement, 0.0,
            f"Mean generational ΔS_E={mean_improvement:.4f} {'>' if passed else '≤'} 0"
        )

    @staticmethod
    def check_fusion_preserves_capabilities(
        r_old_values: List[float],
        min_retention: float = 0.7,
    ) -> FalsificationResult:
        """Failure E: Fusion consistently destroys parent capabilities."""
        if not r_old_values:
            return FalsificationResult("E", False, 0.0, min_retention, "No retention data")
        mean_r = sum(r_old_values) / len(r_old_values)
        passed = mean_r >= min_retention
        return FalsificationResult(
            "E", passed, mean_r, min_retention,
            f"Mean R_old={mean_r:.3f} {'≥' if passed else '<'} {min_retention}"
        )

    @staticmethod
    def check_compression_advantage(
        c_r: float,
        min_compression: float = 2.0,
    ) -> FalsificationResult:
        """Failure F: C_R ~ 1 (no compression advantage)."""
        passed = c_r >= min_compression
        return FalsificationResult(
            "F", passed, c_r, min_compression,
            f"C_R={c_r:.2f} {'≥' if passed else '<'} {min_compression}"
        )

    @classmethod
    def run_all_checks(
        cls,
        s_e_values: Optional[List[float]] = None,
        e_k_values: Optional[List[float]] = None,
        s_e_svd: Optional[float] = None,
        s_e_cppn: Optional[float] = None,
        s_e_per_generation: Optional[List[float]] = None,
        r_old_values: Optional[List[float]] = None,
        c_r: Optional[float] = None,
    ) -> List[FalsificationResult]:
        """Runs all applicable falsification checks and returns results."""
        results = []
        if s_e_values is not None:
            results.append(cls.check_sample_efficiency(s_e_values))
        if e_k_values is not None and s_e_values is not None:
            results.append(cls.check_energy_transfer_correlation(e_k_values, s_e_values))
        if s_e_svd is not None and s_e_cppn is not None:
            results.append(cls.check_cppn_preserves_transfer(s_e_svd, s_e_cppn))
        if s_e_per_generation is not None:
            results.append(cls.check_generational_improvement(s_e_per_generation))
        if r_old_values is not None:
            results.append(cls.check_fusion_preserves_capabilities(r_old_values))
        if c_r is not None:
            results.append(cls.check_compression_advantage(c_r))
        return results
